name: AUR/publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup aur repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          cat <<-EOF >> ~/.ssh/config
            Host aur.archlinux.org
              IdentityFile ~/.ssh/aur
              User aur
          EOF

          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" \
            > ~/.ssh/known_hosts

          chmod -R 0700 ~/.ssh

          git config --local user.name ${{ secrets.AUR_USERNAME }}
          git config --local user.email ${{ secrets.AUR_EMAIL }}
      - name: Update and push release to aur & github
        run: |
          ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORIGIN: ssh://aur@aur.archlinux.org/miru-bin.git